/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colasucia;

import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JLabel;

/**
 *
 * @author iaoco
 */
public class VistaJuego extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VistaJuego(String titulo) {
        super(titulo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Marco = new javax.swing.JPanel();
        Carta = new javax.swing.JLabel();
        BotonTomar = new javax.swing.JButton();
        PuntajeTexto = new javax.swing.JLabel();
        PuntajeNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cola Sucia");
        setBackground(new java.awt.Color(153, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 400, 300));

        Titulo.setFont(new java.awt.Font("Pacifico", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Cola Sucia");

        Marco.setBackground(new java.awt.Color(255, 255, 255));
        Marco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 5, true));

        Carta.setText("-Carta-");

        javax.swing.GroupLayout MarcoLayout = new javax.swing.GroupLayout(Marco);
        Marco.setLayout(MarcoLayout);
        MarcoLayout.setHorizontalGroup(
            MarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarcoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Carta)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        MarcoLayout.setVerticalGroup(
            MarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarcoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Carta)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        BotonTomar.setText("Tomar Carta");
        BotonTomar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonTomarMouseClicked(evt);
            }
        });
        BotonTomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTomarActionPerformed(evt);
            }
        });

        PuntajeTexto.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        PuntajeTexto.setForeground(new java.awt.Color(255, 255, 255));
        PuntajeTexto.setText("Puntaje:");

        PuntajeNum.setForeground(new java.awt.Color(255, 255, 255));
        PuntajeNum.setText("-Puntos-");
        PuntajeNum.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PuntajeNumPropertyChange(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/Fondo2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(Titulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(Marco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(BotonTomar)
                .addGap(37, 37, 37)
                .addComponent(PuntajeTexto)
                .addGap(6, 6, 6)
                .addComponent(PuntajeNum))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(Titulo)
                .addGap(11, 11, 11)
                .addComponent(Marco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonTomar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(PuntajeTexto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(PuntajeNum))))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTomarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BotonTomarActionPerformed

    private void PuntajeNumPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PuntajeNumPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_PuntajeNumPropertyChange

    private void BotonTomarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTomarMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BotonTomarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJuego("Cola Sucia").setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonTomar;
    private javax.swing.JLabel Carta;
    private javax.swing.JPanel Marco;
    private javax.swing.JLabel PuntajeNum;
    private javax.swing.JLabel PuntajeTexto;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JLabel getPuntajeNum() {
        return PuntajeNum;
    }

        public JLabel getCarta() {
        return Carta;
    }

    public void BotonTomarListener(ActionListener al) {
        this.BotonTomar.addActionListener(al);
    }    
}
